version: '3.7'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'home_management'
      MYSQL_PASSWORD: '4321'
      MYSQL_ROOT_PASSWORD: '4321'
    ports:
      - '3306:3306'
